---
# tasks file for apache
- name: install apache
  apt:
    name: apache2
    state: latest
  become: yes


- name: upload apache config file
  template:
     src: apache.conf.j2
     dest: "{{ apache_conf_file }}"
  become: yes


- name: restart apache
  service:
     name: apache2
     state: started
     enabled: yes
  become: yes
